### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/scenery#1]
@indigoxela - Congrats on another very attractive contrib theme. I'm testing this right now and it looks great and I think it fills a nice niche in our contrib space. Love the name and functionality. 

Not sure if you are ready for feedback yet.

**Comment by indigoxela** [comment]
Feedback is always welcome. :+1:

**Comment by indigoxela** [comment]
As of today this theme is sort of almost ready. So if you have some feedback (or bugreports) just go for it. :wink:

**Comment by Egmund** [comment]
Great theme - thanks!
Would it be possible to have different 'scenery' (banner picture) on different pages?
It would be a little too much to clone the theme for every page.

**Comment by indigoxela** [comment]
> Would it be possible to have different 'scenery' (banner picture) on different pages?

Not with the theme alone, but you might be able to achieve what you want with the [Background Images Formatter](https://backdropcms.org/project/bg_image_formatter) module. It's worth a try.

**Comment by Egmund** [comment]
Looking at Background Image Formatter. There seems to be no instructions or examples - so I am lost unfortunately.

**Comment by indigoxela** [comment]
> I am lost unfortunately.

It works with node fields. Add an image field to your node type, add images to nodes, set the display mode to "background image", and as selector choose `.l-header-inner`. That should do the trick.

**Comment by Egmund** [comment]
Thank you for taking the time.
I added a picture field to 'pages' type content, added a pic to one page. There is nowhere any option to set display mode to 'background-image' nor selector. I am probably in the wrong place.

**Comment by indigoxela** [comment]
> There is nowhere any option to set display mode...

Go to /admin/structure/types/manage/page/display/default (Structure > Content types > Page > Manage displays) to manage the field display. There you can set the format to Background image.

**Comment by Egmund** [comment]
Ah yes. Thank you very much - I overlooked that one.
And after setting the selector and size 'cover', position to'center center' all is beautiful.
You are right, this is simple to use.
