### ISSUE TITLE
Video instead of custom background image

### ISSUE THREAD

**Issue by Egmund** [backdrop-contrib/scenery#13]
I am using this great theme for several of my customers.
One customer though insist on video instead of image in the head. Would that be easy to implement or??
I was thinking of adding a 'type' of mp4 to allowed images maybe.

**Comment by indigoxela** [comment]
> One customer though insist on video instead of image in the head.

Oops, on every page? Try to convince them, that this is a bad, bad idea (which it is). :wink: A performance killer for some eye candy, no visitor will ever be happy with.

> I was thinking of adding a 'type' of mp4 to allowed images maybe.

No, that won't work. Backdrop won't accept a video as image.

It's for sure feasible in a custom subtheme, with some extra coding. But not out of the box. At least, it's not supposed to work. :wink:

**Comment by indigoxela** [comment]
Another idea, if you can't convince your customer: Give the [Video Hero Block](https://backdropcms.org/project/video_hero) module a try. It's not the header, though.

**Comment by Egmund** [comment]
Thank you for getting back to me so quickly.
This customer insist on video - I think have to be head - on every page. Even worse, different videos on different pages.
I will try the video hero block or convince him to use smaller videos inside the main content.

**Comment by indigoxela** [comment]
> I will try the video hero block or convince him to use smaller videos inside the main content.

Wishing you all the best. :crossed_fingers: Sometimes customers come up with weird ideas... :shrug:
