### ISSUE TITLE
Footer doesn't always get pushed to bottom

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/scenery#2]
![image](https://user-images.githubusercontent.com/3144571/144392443-b3f12feb-b259-42ca-a700-2b5a04f435c9.png)

I wasn't sure if you are ready for this kind of feedback, because you might be aware of these issues already and just haven't gotten to them. But, I commonly see this problem in contrib themes and find it quite frustrating that on pages without much or any content, the footer does not get pushed to the bottom.

**Comment by indigoxela** [comment]
Yes, it's not ready yet, there are still many todo's. Could it be, you're a bit impatient? :grin:

Anyway, it's OK to report things here in the queue. So there's no chance to miss it before release.

**Comment by stpaultim** [comment]
I'm always excited to see new themes and you have created some really cool ones! So, I suppose I am a bit impatient. 
Thanks for creating this.
