### ISSUE TITLE
Front Page with new content type

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/scenery#3]
FYI

![scenery-cards](https://user-images.githubusercontent.com/3144571/165418203-3d69e9ea-095e-4800-845b-2f1a065f3c33.png)

**Comment by indigoxela** [comment]
Pretty ugly, right? :laughing:

No, seriously, I do have a fix locally, but didn't push it yet. I'm a bit concerned that the images will change, so I wait until I have more trust that they won't.

**Comment by indigoxela** [comment]
Should be fixed in https://github.com/backdrop-contrib/scenery/releases/tag/1.x-1.0.1
